rabbitmq.exchange.internal=internal.exchange
rabbitmq.queue.notification=notification.queue
rabbitmq.routing-key.internal-notification=internal.notification.routing-key
rabbitmq.queue.order-view=order-view.queue
rabbitmq.routing-key.internal-order=internal.order.routing-key

# Saga: Place Order (Choreography)
rabbitmq.queue.saga-place-order=saga.place-order.queue
rabbitmq.routing-key.saga-place-order=saga.place-order.routing-key
rabbitmq.queue.saga-stock-reserved=saga.stock-reserved.queue
rabbitmq.routing-key.saga-stock-reserved=saga.stock-reserved.routing-key
rabbitmq.queue.saga-stock-failed=saga.stock-failed.queue
rabbitmq.routing-key.saga-stock-failed=saga.stock-failed.routing-key
rabbitmq.queue.saga-payment-completed=saga.payment-completed.queue
rabbitmq.routing-key.saga-payment-completed=saga.payment-completed.routing-key
rabbitmq.queue.saga-payment-failed-order=saga.payment-failed.order.queue
rabbitmq.queue.saga-payment-failed-product=saga.payment-failed.product.queue
rabbitmq.routing-key.saga-payment-failed=saga.payment-failed.routing-key
