#Server
server:
  port: 8004
  servlet:
    context-path: /notification
  error:
    include-message: always

#Management
management:
  observations:
    key-values:
      application: ${spring.application.name}
  tracing:
    sampling:
      probability: 1.0
    enabled: true
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

#Spring
spring:
  application:
    name: notification
  datasource:
    url: jdbc:postgresql://demo-microservices.csetxdk14qax.us-east-1.rds.amazonaws.com:5432/notification
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  rabbitmq:
    addresses: rabbitmq:5672
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

#RabbitMQ
rabbitmq:
  exchange:
    internal: internal.exchange
  queue:
    notification: notification.queue
  routing-key:
    internal-notification: internal.notification.routing-key
