#Server
server:
  port: 8765

#Spring
spring:
  application:
    name: gateway
  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true
  security:
    api-key:
      enabled: false
  cloud:
    gateway:
      routes:
        - id: customer
          uri: lb://CUSTOMER # lb = load balancer
          predicates:
            - Path=/api/v1/customers/**
        - id: product
          uri: lb://PRODUCT
          predicates:
            - Path=/api/v1/products/**
        - id: order
          uri: lb://ORDER
          predicates:
            - Path=/api/v1/orders/**
        - id: payment
          uri: lb://PAYMENT
          predicates:
            - Path=/api/v1/payments/**
        - id: notification
          uri: lb://NOTIFICATION
          predicates:
            - Path=/api/v1/notifications/**
        - id: apikey-manager
          uri: lb://APIKEY-MANAGER
          predicates:
            - Path=/api/v1/apiKey-manager/**
  config:
    import:
      - "classpath:shared-application-${spring.profiles.active}.yml"
      - "classpath:clients-${spring.profiles.active}.properties"

#Circuit Breaker
resilience4j:
  circuitbreaker:
    instances:
      apiKeyAuthorization:
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
