#Server
server:
  port: 8006
#Management
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
#Spring
spring:
  application:
    name: gateway
  zipkin:
    base-url: http://localhost:9411
  cloud:
    gateway:
      routes:
        - id: customer
          uri: lb://CUSTOMER # lb = load balancer
          predicates:
              - Path=/customer/api/v1/customers/**
        - id: product
          uri: lb://PRODUCT
          predicates:
              - Path=/product/api/v1/products/**
        - id: order
          uri: lb://ORDER
          predicates:
              - Path=/order/api/v1/orders/**
        - id: payment
          uri: lb://PAYMENT
          predicates:
            - Path=/payment/api/v1/payments/**
        - id: notification
          uri: lb://NOTIFICATION
          predicates:
              - Path=/notification/api/v1/notifications/**
#Eureka-Client
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
