apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/actuator/prometheus"
        prometheus.io/port: "8005"
    spec:
      containers:
        - name: payment
          image: miliariadnane/payment:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8005
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: kube
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: DB_PASSWORD
          resources:
            requests:
              cpu: "200m"
      restartPolicy: Always
