management:
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/${spring.application.name}
    username: miliariadnane
    password: password
  rabbitmq:
    addresses: rabbitmq:5672
  sql:
    init:
      mode: always
      data-locations: classpath*:db/data.sql
      platform: postgresql

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
    enabled: false
